# Generated by Django 2.1.2 on 2018-12-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labevents', '0002_labevent_valueom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labevent',
            name='charttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
