# Generated by Django 2.1.2 on 2018-12-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dose_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
