# Generated by Django 2.1.2 on 2018-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_dose_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prod_strength',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
