# Generated by Django 2.1.2 on 2018-12-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_auto_20181210_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dose_val',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
