# Generated by Django 2.1.2 on 2018-12-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171024_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_location',
            field=models.TextField(blank=True, null=True, verbose_name='admission_location'),
        ),
        migrations.AddField(
            model_name='user',
            name='admission_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='admission_type'),
        ),
        migrations.AddField(
            model_name='user',
            name='admittime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='admittime'),
        ),
        migrations.AddField(
            model_name='user',
            name='deathtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deathtime'),
        ),
        migrations.AddField(
            model_name='user',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='diagnosis'),
        ),
        migrations.AddField(
            model_name='user',
            name='discharge_location',
            field=models.TextField(blank=True, null=True, verbose_name='discharge_location'),
        ),
        migrations.AddField(
            model_name='user',
            name='dischtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dischtime'),
        ),
        migrations.AddField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ethnicity'),
        ),
        migrations.AddField(
            model_name='user',
            name='hadm_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='hadm_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='insurance'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='user',
            name='martial_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='martial_status'),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='religion'),
        ),
    ]
