# Generated by Django 2.1.2 on 2018-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181210_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='user',
            name='statement',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='statement'),
        ),
    ]
