# Generated by Django 2.1.2 on 2018-12-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181210_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='statement',
            field=models.TextField(blank=True, null=True, verbose_name='statement'),
        ),
    ]
